version: '3'
services:
  dev:
    image: awsdocker13rl/mm-dev
    container_name: mm-dev-client
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev-client
volumes:
  node_modules:
